CREATE TABLE LOGS(
    SESSION_ID VARCHAR(50) PRIMARY KEY NOT NULL,
    USER_ID VARCHAR(16) NOT NULL
);

CREATE TABLE ACTIONS(
    ACT_ID VARCHAR(50) PRIMARY KEY NOT NULL,
    SESSION_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(16) NOT NULL,
    TIME VARCHAR(30)NOT NULL,
    TYPE VARCHAR(10)NOT NULL
);

CREATE TABLE PROPERTIES(
    PROP_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    ACT_ID VARCHAR(50) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    LOCATION_X LONG(20),
    LOCATION_Y LONG(20),
    VIEWED_ID VARCHAR(20),
    PAGE_FROM VARCHAR(20),
    PAGE_TO VARCHAR(20)
);

ALTER TABLE ACTIONS ADD FOREIGN KEY (SESSION_ID) REFERENCES LOGS(SESSION_ID);
ALTER TABLE PROPERTIES ADD FOREIGN KEY (ACT_ID) REFERENCES ACTIONS(ACT_ID);

